# Generated by Django 6.0 on 2025-12-12 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_uploadeddocument_owner_agent'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='api_key',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
